### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by Hywan**
And thanks for the tool!

### CODE REVIEW

**Comment by mpnkhan** [comment]
Wonderful! Thank you :-)

**Comment by Frank703** [comment]
Hi mpnkhan, thank you for the great tool. I have one question. Current AATT api supports Section508 testing too? if yes, how do i configure it? Thank you in advance. -Frank

**Comment by mpnkhan** [comment]
Currently it doesn't support Section508. It supports WCAG2AA, WCAG2A, WCAG2AAA through an option called "level".  Defaults to WCAG2A

**Comment by mpnkhan** [comment]
Added some support for Section508.

**Pull request merged**
